import { Project } from '../../../../../domain/entities/project.entity';

export const seedProjects: Project[] = [
  new Project({
    id: '1',
    name: 'Portfolio API',
    description:
      'RESTful API for personal portfolio website built with NestJS and hexagonal architecture. Provides endpoints for skills, experiences, education, and projects with in-memory data storage and comprehensive e2e test coverage.',
    startDate: new Date('2024-12-01'),
    endDate: null,
    technologies: ['TypeScript', 'NestJS', 'Node.js', 'Jest', 'Docker'],
    repositoryLink: 'https://github.com/tonytangdev/portfolio-api',
    demoLink: 'https://api.tonytang.dev',
    websiteLink: null,
    achievements: [
      'Implemented clean hexagonal architecture with clear separation of concerns',
      'Achieved 100% e2e test coverage for all endpoints',
      'Configured modular system with environment-based feature toggles',
      'Applied SOLID principles and clean code practices throughout',
    ],
    order: 0,
    isHighlighted: true,
  }),
  new Project({
    id: '2',
    name: 'E-commerce Platform',
    description:
      'Full-stack e-commerce application with product catalog, shopping cart, checkout flow, and payment integration. Features real-time inventory management and order tracking.',
    startDate: new Date('2023-06-01'),
    endDate: new Date('2024-03-15'),
    technologies: [
      'TypeScript',
      'React',
      'Next.js',
      'PostgreSQL',
      'Stripe',
      'Redis',
      'Tailwind CSS',
    ],
    repositoryLink: null,
    demoLink: 'https://shop-demo.example.com',
    websiteLink: 'https://shop.example.com',
    achievements: [
      'Integrated Stripe payment processing with secure checkout flow',
      'Built admin dashboard for inventory and order management',
      'Implemented Redis caching reducing database load by 60%',
      'Achieved sub-2 second page load times with Next.js optimization',
    ],
    order: 1,
    isHighlighted: true,
  }),
  new Project({
    id: '3',
    name: 'Task Management App',
    description:
      'Collaborative task management application with real-time updates, team workspaces, and project boards. Supports drag-and-drop interface and deadline tracking.',
    startDate: new Date('2023-01-15'),
    endDate: new Date('2023-08-30'),
    technologies: [
      'Vue.js',
      'TypeScript',
      'Express',
      'MongoDB',
      'Socket.io',
      'Vuetify',
    ],
    repositoryLink: 'https://github.com/tonytangdev/task-manager',
    demoLink: null,
    websiteLink: null,
    achievements: [
      'Implemented real-time collaboration using WebSockets',
      'Built drag-and-drop Kanban board with smooth animations',
      'Designed flexible permission system for team collaboration',
      'Supported 500+ concurrent users in testing',
    ],
    order: 2,
    isHighlighted: false,
  }),
  new Project({
    id: '4',
    name: 'Weather Dashboard',
    description:
      'Interactive weather dashboard displaying current conditions, forecasts, and weather maps. Features location search, favorite locations, and responsive design.',
    startDate: new Date('2022-09-01'),
    endDate: new Date('2022-11-30'),
    technologies: [
      'JavaScript',
      'React',
      'OpenWeatherMap API',
      'Chart.js',
      'CSS3',
    ],
    repositoryLink: 'https://github.com/tonytangdev/weather-dashboard',
    demoLink: 'https://weather.tonytang.dev',
    websiteLink: null,
    achievements: [
      'Integrated third-party weather API with efficient caching',
      'Built responsive design working on mobile and desktop',
      'Created interactive charts for temperature and precipitation trends',
      'Implemented progressive web app features for offline support',
    ],
    order: 3,
    isHighlighted: false,
  }),
  new Project({
    id: '5',
    name: 'Blog Platform',
    description:
      'Headless CMS-powered blog platform with markdown support, code syntax highlighting, and SEO optimization. Features admin panel for content management.',
    startDate: new Date('2022-03-01'),
    endDate: new Date('2022-07-15'),
    technologies: [
      'Next.js',
      'TypeScript',
      'Contentful',
      'MDX',
      'Tailwind CSS',
      'Vercel',
    ],
    repositoryLink: 'https://github.com/tonytangdev/blog',
    demoLink: null,
    websiteLink: 'https://blog.tonytang.dev',
    achievements: [
      'Integrated Contentful headless CMS for flexible content management',
      'Implemented server-side rendering for optimal SEO',
      'Built custom MDX components for rich content formatting',
      'Achieved 100/100 Lighthouse SEO score',
    ],
    order: 4,
    isHighlighted: false,
  }),
];
